name: API Tests

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      - name: Check and build application
        run:
          docker-compose build

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run application
        run: |
          docker-compose up -d

      - name: Waiting for application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:8080
          echo "Application is up"

      - name: Run Postman tests
        run: |
          newman run ./postman/Yandex_Lavka.postman_collection.json \
          --delay-request 50 -r cli,htmlextra \
          --verbose --color on --reporter-htmlextra-darkTheme \
          --reporter-htmlextra-export reports/ewm_main_report.html \
          --reporter-htmlextra-title "Report results" \
          --reporter-htmlextra-logs true \

      - name: Compose down
        run: docker-compose down
