name: API Tests

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check and build application
        run:
          docker-compose build

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run application
        run: |
          docker image list
          docker container list
          docker logs yandex-academy-2023_application_1
          chmod +x .github/workflows/wait-for-it.sh
          .github/workflows/wait-for-it.sh -t 60 http://127.0.0.1:80

      - name: Curl get
        run: curl -X GET http://127.0.0.1:80

      - name: iptables -nvL
        run: sudo iptables -nvL

      - name: Find localhost
        run: nslookup localhost

      - name: Find Network
        run: networkctl list

      - name: plntu
        run: netstat -plntu

      - name: plntu
        run: netstat -plntu

      - name: networkctl status eth0
        run: networkctl status eth0

      - name: Run Postman tests
        run: |
          newman run ./postman/Yandex_Lavka.postman_collection.json \
          --delay-request 50 -r cli,htmlextra \
          --verbose --color on --reporter-htmlextra-darkTheme \
          --reporter-htmlextra-export reports/ewm_main_report.html \
          --reporter-htmlextra-title "Report results" \
          --reporter-htmlextra-logs true \

      - name: Compose down
        run: docker-compose down
