name: API Tests

on:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check and Build application
        run:
          docker-compose build

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.16.0'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run application
        run:
          docker-compose up -d
          .github/workflows/wait-for-it.sh -t 60 localhost:8080
          .github/workflows/wait-for-it.sh -t 60 localhost:9090
          docker-compose ps
          docker-compose logs

      - name: Run POSTMAN tests
        run: >
          newman run ./postman/Yandex_Lavka.postman_collection.json 
          --delay-request 50 -r cli,htmlextra 
          --verbose --color on --reporter-htmlextra-darkTheme 
          --reporter-htmlextra-export reports/ewm_main_report.html
          --reporter-htmlextra-title "Report"
          --reporter-htmlextra-logs true
          --reporter-htmlextra-template ./tests/.github/workflows/dashboard-template.hbs

      - name: Compose down
        run: |
          docker-compose down
