name: Docker Image CI

on:
  push:
  pull_request:
  workflow_call:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: docker-compose up -d
